# Generated by Django 6.0.8 on 2026-09-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(default="eu-west", max_length=32)),
                ("status", models.CharField(default="idle", max_length=32)),
                ("archived", models.BooleanField(default=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "last_report",
                    models.JSONField(blank=True, help_text="Rendered read-only.", null=True),
                ),
            ],
            options={
                "ordering": ("pk",),
                "permissions": [("purge_device", "Can purge devices")],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="demoapp.device",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
