# Generated by Django 6.0.8 on 2026-09-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="recorded_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reading",
            name="value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
