# Generated by Django 6.0.8 on 2026-09-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0002_range_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="device",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="devices", to="demoapp.tag"),
        ),
    ]
