# Generated by Django 6.0.8 on 2026-09-24 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demoapp", "0003_choice_filters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ("pk",),
                "permissions": [
                    ("purge_device", "Can purge devices"),
                    ("run_demo_report", "Can run the demo report"),
                ],
            },
        ),
    ]
